# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-10 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_userprofile_user_type_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_access_userprofile_list', '可以访问用户表'), ('can_add_userprofile_get', '可以访问添加用户表界面'), ('can_add_userprofile_post', '可以添加用户表记录'), ('can_change_userprofile_get', '可以访问修改用户表记录')), 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type_id',
            field=models.IntegerField(choices=[(1, '超级用户'), (2, '普通用户'), (6, '普普通用户')], default=1),
        ),
    ]
